# Generated by Django 4.1.4 on 2023-02-01 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0002_alter_reviews_reviewername'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='myUser',
        ),
    ]
